### ISSUE TITLE
Possible to update it to work with the discord api in 2021

### ISSUE THREAD

**Issue by quorn23** [enzobes/WarezBot#12]
The bot used to work, but a friend just made me aware it stopped working, would it be possible to update it to make it work with the current discord api etc?

**Comment by enzobes** [comment]
I'll see when I have some time to update it thanks for your interest. I'll let you know here when it's working

**Comment by hamzzzXI** [comment]
I second the request above.

**Comment by enzobes** [comment]
Update here : https://github.com/enzobes/WarezBot/commit/320a4f63214b7c842fa8f8c124fa396d681398f6

**Comment by quorn23** [comment]
Thank you enzobes, build the image and works fine again :) 
fyi if i pull it from docker hub it didn't work. Not sure if the changes are properly pushed
