### ISSUE TITLE
Layer13 down :( - Add an Alternative?

### ISSUE THREAD

**Issue by STX2k** [enzobes/WarezBot#9]
It seems Layer13 is shutting down. Do you plan a alternative for your Bot? 

- pre.corrupt-net.org
- predb.pw

Greets STX2k

**Comment by enzobes** [comment]
I would like indeed.
I will add an alternative as soon as possible. 
But pre.corrupt-net.org and predb.pw doesn't have an API for the requests

**Comment by STX2k** [comment]
Okay i check some sites .. 

https://predb.org/about -> Have API

**Comment by enzobes** [comment]
Yes, I will check that soon 
Thank for you help :+1: 
MAJ: I send a form to have access to the API

**Comment by enzobes** [comment]
I have an access to the API I will see what can I do with 👍

**Comment by hencolque** [comment]
some guy wants to buy layer13 backup to 1000 USD

**Comment by dydus25** [comment]
best archive nfo : http://dupefr.com

**Comment by enzobes** [comment]
They don't have an API
